/**
 * Distinctive words from the held-out items. Seeds may not contain these even inside longer phrases
 * (e.g. "ilish mach"), or the held-out score would measure lookup instead of generalization.
 */
export const HELDOUT_KEY_TERMS = [
    'shawarma', 'chicken fry', 'pizza hut', 'starbucks', 'jhalmuri', 'khichuri', 'bhat', 'biscuit', 'বার্গার', 'ইফতার',
    'দই ফুচকা', 'tomato', 'cauliflower', 'potol', 'begun', 'lau', 'rui', 'ilish', 'mosur', 'ইলিশ', 'চিংড়ি', 'ডজন',
    'bike ride', 'indrive', 'motorcycle', 'train er ticket', 'ট্যাক্সি', 'বিমান',
    'prepaid meter', 'electricity token', 'broadband bill', 'gp', 'robi', 'পানি বিল',
    'tshirt', 'sneakers', 'earphone', 'power bank', 'aarong', 'sunglass', 'eid er jama', 'ঈদের', 'চাদর',
    'ace plus', 'insulin', 'eye drop', 'dental', 'blood sugar', 'oshud', 'ঔষধ', 'দেখালাম',
    'concert ticket', 'bowling', 'prime video', 'ps5', 'nandan park', 'ঈদে',
    'ielts', 'udemy', 'semester', 'photocopy', 'ssc', 'admission coaching', 'স্কুলের',
    'beard', 'facewash', 'deodorant', 'gym membership', 'chul katano', 'নাপিত',
    'upwork', 'fiverr', 'eid bonus', 'bank interest', 'mash er beton', 'project payment', 'office theke', 'পেয়েছি',
];

/**
 * Category-only test items that are NOT in seeds.json (enforced by a test), so accuracy here
 * measures how well the embedding generalizes rather than exact lookups.
 */
export const HELDOUT_ITEMS: Array<{ text: string; category: string; lang: 'en' | 'banglish' | 'bangla' }> = [
    // Food & Dining
    { text: 'shawarma', category: 'Food & Dining', lang: 'en' },
    { text: 'chicken fry', category: 'Food & Dining', lang: 'en' },
    { text: 'pizza hut', category: 'Food & Dining', lang: 'en' },
    { text: 'starbucks', category: 'Food & Dining', lang: 'en' },
    { text: 'jhalmuri', category: 'Food & Dining', lang: 'banglish' },
    { text: 'khichuri', category: 'Food & Dining', lang: 'banglish' },
    { text: 'dupure bhat khelam', category: 'Food & Dining', lang: 'banglish' },
    { text: 'cha r biscuit', category: 'Food & Dining', lang: 'banglish' },
    { text: 'বার্গার', category: 'Food & Dining', lang: 'bangla' },
    { text: 'ইফতার', category: 'Food & Dining', lang: 'bangla' },
    { text: 'দই ফুচকা', category: 'Food & Dining', lang: 'bangla' },

    // Groceries
    { text: 'tomato', category: 'Groceries', lang: 'en' },
    { text: 'cauliflower', category: 'Groceries', lang: 'en' },
    { text: 'potol', category: 'Groceries', lang: 'banglish' },
    { text: 'begun', category: 'Groceries', lang: 'banglish' },
    { text: 'lau', category: 'Groceries', lang: 'banglish' },
    { text: 'rui mach', category: 'Groceries', lang: 'banglish' },
    { text: 'ilish', category: 'Groceries', lang: 'banglish' },
    { text: 'mosur dal', category: 'Groceries', lang: 'banglish' },
    { text: 'ইলিশ মাছ', category: 'Groceries', lang: 'bangla' },
    { text: 'চিংড়ি', category: 'Groceries', lang: 'bangla' },
    { text: 'ডিম এক ডজন', category: 'Groceries', lang: 'bangla' },

    // Transport
    { text: 'bike ride', category: 'Transport', lang: 'en' },
    { text: 'indrive', category: 'Transport', lang: 'en' },
    { text: 'motorcycle servicing', category: 'Transport', lang: 'en' },
    { text: 'pathao bike', category: 'Transport', lang: 'banglish' },
    { text: 'uber e office', category: 'Transport', lang: 'banglish' },
    { text: 'cng te gelam', category: 'Transport', lang: 'banglish' },
    { text: 'train er ticket', category: 'Transport', lang: 'banglish' },
    { text: 'ট্যাক্সি', category: 'Transport', lang: 'bangla' },
    { text: 'বিমান টিকিট', category: 'Transport', lang: 'bangla' },

    // Bills & Utilities
    { text: 'prepaid meter recharge', category: 'Bills & Utilities', lang: 'en' },
    { text: 'electricity token', category: 'Bills & Utilities', lang: 'en' },
    { text: 'broadband bill', category: 'Bills & Utilities', lang: 'en' },
    { text: 'current bill dilam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'gp recharge', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'robi recharge', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'পানি বিল', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'বাসা ভাড়া দিলাম', category: 'Bills & Utilities', lang: 'bangla' },

    // Shopping
    { text: 'tshirt', category: 'Shopping', lang: 'en' },
    { text: 'sneakers', category: 'Shopping', lang: 'en' },
    { text: 'earphone', category: 'Shopping', lang: 'en' },
    { text: 'power bank', category: 'Shopping', lang: 'en' },
    { text: 'aarong', category: 'Shopping', lang: 'en' },
    { text: 'sunglass', category: 'Shopping', lang: 'en' },
    { text: 'eid er jama', category: 'Shopping', lang: 'banglish' },
    { text: 'ঈদের জামা', category: 'Shopping', lang: 'bangla' },
    { text: 'বিছানার চাদর', category: 'Shopping', lang: 'bangla' },

    // Healthcare
    { text: 'ace plus', category: 'Healthcare', lang: 'en' },
    { text: 'insulin', category: 'Healthcare', lang: 'en' },
    { text: 'eye drop', category: 'Healthcare', lang: 'en' },
    { text: 'dental checkup', category: 'Healthcare', lang: 'en' },
    { text: 'blood sugar test', category: 'Healthcare', lang: 'en' },
    { text: 'oshud kinlam', category: 'Healthcare', lang: 'banglish' },
    { text: 'hospital e test', category: 'Healthcare', lang: 'banglish' },
    { text: 'ঔষধ', category: 'Healthcare', lang: 'bangla' },
    { text: 'ডাক্তার দেখালাম', category: 'Healthcare', lang: 'bangla' },

    // Entertainment
    { text: 'concert ticket', category: 'Entertainment', lang: 'en' },
    { text: 'bowling', category: 'Entertainment', lang: 'en' },
    { text: 'prime video', category: 'Entertainment', lang: 'en' },
    { text: 'ps5 game', category: 'Entertainment', lang: 'en' },
    { text: 'hoichoi subscription', category: 'Entertainment', lang: 'banglish' },
    { text: 'nandan park', category: 'Entertainment', lang: 'banglish' },
    { text: 'ঈদে ঘুরতে গেলাম', category: 'Entertainment', lang: 'bangla' },

    // Education
    { text: 'ielts fee', category: 'Education', lang: 'en' },
    { text: 'udemy course', category: 'Education', lang: 'en' },
    { text: 'university semester fee', category: 'Education', lang: 'en' },
    { text: 'class notes photocopy', category: 'Education', lang: 'en' },
    { text: 'ssc form fill up', category: 'Education', lang: 'banglish' },
    { text: 'admission coaching', category: 'Education', lang: 'banglish' },
    { text: 'স্কুলের ফি', category: 'Education', lang: 'bangla' },

    // Personal Care
    { text: 'beard trim', category: 'Personal Care', lang: 'en' },
    { text: 'facewash', category: 'Personal Care', lang: 'en' },
    { text: 'deodorant', category: 'Personal Care', lang: 'en' },
    { text: 'gym membership', category: 'Personal Care', lang: 'en' },
    { text: 'chul katano', category: 'Personal Care', lang: 'banglish' },
    { text: 'নাপিত', category: 'Personal Care', lang: 'bangla' },

    // Salary / income
    { text: 'upwork payment', category: 'Salary', lang: 'en' },
    { text: 'fiverr', category: 'Salary', lang: 'en' },
    { text: 'eid bonus', category: 'Salary', lang: 'en' },
    { text: 'bank interest', category: 'Salary', lang: 'en' },
    { text: 'mash er beton', category: 'Salary', lang: 'banglish' },
    { text: 'project payment pelam', category: 'Salary', lang: 'banglish' },
    { text: 'office theke taka pelam', category: 'Salary', lang: 'banglish' },
    { text: 'বেতন পেয়েছি', category: 'Salary', lang: 'bangla' },

    // ── Expanded set (300 items, 10 per language per category), written after the v2 seed list. ──
    // Mixes unseen words with new phrasings of seed words; eval reports the two kinds separately.
    // Food & Dining
    { text: 'noodles', category: 'Food & Dining', lang: 'en' },
    { text: 'fried rice', category: 'Food & Dining', lang: 'en' },
    { text: 'hot dog', category: 'Food & Dining', lang: 'en' },
    { text: 'pasta', category: 'Food & Dining', lang: 'en' },
    { text: 'grilled chicken', category: 'Food & Dining', lang: 'en' },
    { text: 'cold coffee', category: 'Food & Dining', lang: 'en' },
    { text: 'dumplings', category: 'Food & Dining', lang: 'en' },
    { text: 'nachos', category: 'Food & Dining', lang: 'en' },
    { text: 'cupcake', category: 'Food & Dining', lang: 'en' },
    { text: 'iced tea', category: 'Food & Dining', lang: 'en' },
    { text: 'mughlai porota', category: 'Food & Dining', lang: 'banglish' },
    { text: 'kabab khelam', category: 'Food & Dining', lang: 'banglish' },
    { text: 'nehari', category: 'Food & Dining', lang: 'banglish' },
    { text: 'falooda', category: 'Food & Dining', lang: 'banglish' },
    { text: 'lassi', category: 'Food & Dining', lang: 'banglish' },
    { text: 'chotpoti khelam', category: 'Food & Dining', lang: 'banglish' },
    { text: 'tong er cha', category: 'Food & Dining', lang: 'banglish' },
    { text: 'canteen e lunch', category: 'Food & Dining', lang: 'banglish' },
    { text: 'bhuna khichuri', category: 'Food & Dining', lang: 'banglish' },
    { text: 'halua', category: 'Food & Dining', lang: 'banglish' },
    { text: 'নুডলস', category: 'Food & Dining', lang: 'bangla' },
    { text: 'কাবাব', category: 'Food & Dining', lang: 'bangla' },
    { text: 'চটপটি খেলাম', category: 'Food & Dining', lang: 'bangla' },
    { text: 'পরোটা ডিম ভাজি', category: 'Food & Dining', lang: 'bangla' },
    { text: 'হালিম খেলাম', category: 'Food & Dining', lang: 'bangla' },
    { text: 'পিঠা', category: 'Food & Dining', lang: 'bangla' },
    { text: 'হালুয়া', category: 'Food & Dining', lang: 'bangla' },
    { text: 'রোস্ট', category: 'Food & Dining', lang: 'bangla' },
    { text: 'চিকেন ফ্রাই খেলাম', category: 'Food & Dining', lang: 'bangla' },
    { text: 'ফ্রাইড রাইস', category: 'Food & Dining', lang: 'bangla' },

    // Groceries
    { text: 'cucumber', category: 'Groceries', lang: 'en' },
    { text: 'carrot', category: 'Groceries', lang: 'en' },
    { text: 'spinach', category: 'Groceries', lang: 'en' },
    { text: 'lemon', category: 'Groceries', lang: 'en' },
    { text: 'zucchini', category: 'Groceries', lang: 'en' },
    { text: 'broccoli', category: 'Groceries', lang: 'en' },
    { text: 'pumpkin', category: 'Groceries', lang: 'en' },
    { text: 'beetroot', category: 'Groceries', lang: 'en' },
    { text: 'cornflakes', category: 'Groceries', lang: 'en' },
    { text: 'peanut butter', category: 'Groceries', lang: 'en' },
    { text: 'kancha morich', category: 'Groceries', lang: 'banglish' },
    { text: 'tilapia mach', category: 'Groceries', lang: 'banglish' },
    { text: 'kumra', category: 'Groceries', lang: 'banglish' },
    { text: 'pui shak', category: 'Groceries', lang: 'banglish' },
    { text: 'kochur loti', category: 'Groceries', lang: 'banglish' },
    { text: 'chalkumra', category: 'Groceries', lang: 'banglish' },
    { text: 'kakrol', category: 'Groceries', lang: 'banglish' },
    { text: 'puti mach', category: 'Groceries', lang: 'banglish' },
    { text: 'kachkola', category: 'Groceries', lang: 'banglish' },
    { text: 'mishti kumra', category: 'Groceries', lang: 'banglish' },
    { text: 'কলা', category: 'Groceries', lang: 'bangla' },
    { text: 'আম', category: 'Groceries', lang: 'bangla' },
    { text: 'কুমড়া', category: 'Groceries', lang: 'bangla' },
    { text: 'ঝিঙ্গা', category: 'Groceries', lang: 'bangla' },
    { text: 'ঢেঁড়স', category: 'Groceries', lang: 'bangla' },
    { text: 'শুঁটকি', category: 'Groceries', lang: 'bangla' },
    { text: 'মধু', category: 'Groceries', lang: 'bangla' },
    { text: 'কাঁকরোল', category: 'Groceries', lang: 'bangla' },
    { text: 'চালকুমড়া', category: 'Groceries', lang: 'bangla' },
    { text: 'পুঁটি মাছ', category: 'Groceries', lang: 'bangla' },

    // Transport
    { text: 'airport shuttle', category: 'Transport', lang: 'en' },
    { text: 'tyre change', category: 'Transport', lang: 'en' },
    { text: 'engine oil change', category: 'Transport', lang: 'en' },
    { text: 'bus pass', category: 'Transport', lang: 'en' },
    { text: 'metro card topup', category: 'Transport', lang: 'en' },
    { text: 'cab fare', category: 'Transport', lang: 'en' },
    { text: 'ferry crossing', category: 'Transport', lang: 'en' },
    { text: 'shuttle bus', category: 'Transport', lang: 'en' },
    { text: 'intercity train', category: 'Transport', lang: 'en' },
    { text: 'sleeper bus', category: 'Transport', lang: 'en' },
    { text: 'tempu vara', category: 'Transport', lang: 'banglish' },
    { text: 'nouka vara', category: 'Transport', lang: 'banglish' },
    { text: 'bike e gelam', category: 'Transport', lang: 'banglish' },
    { text: 'uber e bari', category: 'Transport', lang: 'banglish' },
    { text: 'pathao te office', category: 'Transport', lang: 'banglish' },
    { text: 'cng vara dilam', category: 'Transport', lang: 'banglish' },
    { text: 'gari parking', category: 'Transport', lang: 'banglish' },
    { text: 'gari te tel bhorlam', category: 'Transport', lang: 'banglish' },
    { text: 'rickshaw e bazar', category: 'Transport', lang: 'banglish' },
    { text: 'leguna vara', category: 'Transport', lang: 'banglish' },
    { text: 'নৌকা ভাড়া', category: 'Transport', lang: 'bangla' },
    { text: 'অটো ভাড়া', category: 'Transport', lang: 'bangla' },
    { text: 'পাঠাও', category: 'Transport', lang: 'bangla' },
    { text: 'ট্রেনের টিকেট', category: 'Transport', lang: 'bangla' },
    { text: 'গাড়ির তেল', category: 'Transport', lang: 'bangla' },
    { text: 'ফেরি পার', category: 'Transport', lang: 'bangla' },
    { text: 'টেম্পু ভাড়া', category: 'Transport', lang: 'bangla' },
    { text: 'রিকশায় অফিস', category: 'Transport', lang: 'bangla' },
    { text: 'বাসের টিকিট', category: 'Transport', lang: 'bangla' },
    { text: 'চাকা পাংচার', category: 'Transport', lang: 'bangla' },

    // Bills & Utilities
    { text: 'water supply bill', category: 'Bills & Utilities', lang: 'en' },
    { text: 'gas cylinder refill', category: 'Bills & Utilities', lang: 'en' },
    { text: 'internet package', category: 'Bills & Utilities', lang: 'en' },
    { text: 'monthly rent', category: 'Bills & Utilities', lang: 'en' },
    { text: 'lift maintenance', category: 'Bills & Utilities', lang: 'en' },
    { text: 'building guard bill', category: 'Bills & Utilities', lang: 'en' },
    { text: 'cleaner bill', category: 'Bills & Utilities', lang: 'en' },
    { text: 'sim recharge', category: 'Bills & Utilities', lang: 'en' },
    { text: 'meter rent', category: 'Bills & Utilities', lang: 'en' },
    { text: 'electricity due', category: 'Bills & Utilities', lang: 'en' },
    { text: 'gas er bill', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'pani er bill', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'mobile e taka bhorlam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'banglalink e recharge', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'basa vara dilam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'flexi korlam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'dish line bill', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'biddut er bill dilam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'net er bill', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'mb pack kinlam', category: 'Bills & Utilities', lang: 'banglish' },
    { text: 'বিদ্যুতের বিল', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'গ্যাসের বিল', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'ইন্টারনেটের বিল', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'মোবাইলে টাকা ভরলাম', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'রিচার্জ করলাম', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'বাড়িভাড়া', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'ডিশের বিল', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'গ্যাস সিলিন্ডার', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'ইন্টারনেট প্যাক', category: 'Bills & Utilities', lang: 'bangla' },
    { text: 'বিদ্যুৎ বিল পরিশোধ', category: 'Bills & Utilities', lang: 'bangla' },

    // Shopping
    { text: 'winter jacket', category: 'Shopping', lang: 'en' },
    { text: 'smartwatch', category: 'Shopping', lang: 'en' },
    { text: 'phone case', category: 'Shopping', lang: 'en' },
    { text: 'computer mouse', category: 'Shopping', lang: 'en' },
    { text: 'denim jacket', category: 'Shopping', lang: 'en' },
    { text: 'handbag', category: 'Shopping', lang: 'en' },
    { text: 'gaming mouse', category: 'Shopping', lang: 'en' },
    { text: 'blender machine', category: 'Shopping', lang: 'en' },
    { text: 'office bag', category: 'Shopping', lang: 'en' },
    { text: 'phone tripod', category: 'Shopping', lang: 'en' },
    { text: 'notun juta kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'shari kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'panjabi kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'three piece kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'ghori kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'daraz order', category: 'Shopping', lang: 'banglish' },
    { text: 'mobile cover', category: 'Shopping', lang: 'banglish' },
    { text: 'bag kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'jama kapor kinlam', category: 'Shopping', lang: 'banglish' },
    { text: 'jutar dokan', category: 'Shopping', lang: 'banglish' },
    { text: 'জিন্স', category: 'Shopping', lang: 'bangla' },
    { text: 'মানিব্যাগ', category: 'Shopping', lang: 'bangla' },
    { text: 'হেডফোন', category: 'Shopping', lang: 'bangla' },
    { text: 'ফোনের কভার', category: 'Shopping', lang: 'bangla' },
    { text: 'চার্জার কিনলাম', category: 'Shopping', lang: 'bangla' },
    { text: 'দারাজ অর্ডার', category: 'Shopping', lang: 'bangla' },
    { text: 'প্যান্ট', category: 'Shopping', lang: 'bangla' },
    { text: 'ফ্যান কিনলাম', category: 'Shopping', lang: 'bangla' },
    { text: 'টিভি কিনলাম', category: 'Shopping', lang: 'bangla' },
    { text: 'দেয়াল ঘড়ি', category: 'Shopping', lang: 'bangla' },

    // Healthcare
    { text: 'ultrasound', category: 'Healthcare', lang: 'en' },
    { text: 'eye specialist', category: 'Healthcare', lang: 'en' },
    { text: 'child specialist', category: 'Healthcare', lang: 'en' },
    { text: 'vaccine', category: 'Healthcare', lang: 'en' },
    { text: 'cetirizine', category: 'Healthcare', lang: 'en' },
    { text: 'omeprazole', category: 'Healthcare', lang: 'en' },
    { text: 'eye test', category: 'Healthcare', lang: 'en' },
    { text: 'blood pressure machine', category: 'Healthcare', lang: 'en' },
    { text: 'thermometer', category: 'Healthcare', lang: 'en' },
    { text: 'nebulizer', category: 'Healthcare', lang: 'en' },
    { text: 'jor er oshudh', category: 'Healthcare', lang: 'banglish' },
    { text: 'gastric er oshudh', category: 'Healthcare', lang: 'banglish' },
    { text: 'daktar dekhalam', category: 'Healthcare', lang: 'banglish' },
    { text: 'test korate gelam', category: 'Healthcare', lang: 'banglish' },
    { text: 'hospital e bhorti', category: 'Healthcare', lang: 'banglish' },
    { text: 'dater daktar', category: 'Healthcare', lang: 'banglish' },
    { text: 'chokher daktar', category: 'Healthcare', lang: 'banglish' },
    { text: 'pressure mapa', category: 'Healthcare', lang: 'banglish' },
    { text: 'syrup kinlam', category: 'Healthcare', lang: 'banglish' },
    { text: 'injection dilam', category: 'Healthcare', lang: 'banglish' },
    { text: 'জ্বরের ওষুধ', category: 'Healthcare', lang: 'bangla' },
    { text: 'চোখের ডাক্তার', category: 'Healthcare', lang: 'bangla' },
    { text: 'হাসপাতালে ভর্তি', category: 'Healthcare', lang: 'bangla' },
    { text: 'ইনজেকশন', category: 'Healthcare', lang: 'bangla' },
    { text: 'স্যালাইন', category: 'Healthcare', lang: 'bangla' },
    { text: 'প্রেসারের ওষুধ', category: 'Healthcare', lang: 'bangla' },
    { text: 'দাঁত তোলা', category: 'Healthcare', lang: 'bangla' },
    { text: 'অপারেশন', category: 'Healthcare', lang: 'bangla' },
    { text: 'চোখ পরীক্ষা', category: 'Healthcare', lang: 'bangla' },
    { text: 'এক্সরে করলাম', category: 'Healthcare', lang: 'bangla' },

    // Entertainment
    { text: 'theme park', category: 'Entertainment', lang: 'en' },
    { text: 'arcade', category: 'Entertainment', lang: 'en' },
    { text: 'karaoke', category: 'Entertainment', lang: 'en' },
    { text: 'board game', category: 'Entertainment', lang: 'en' },
    { text: 'football match ticket', category: 'Entertainment', lang: 'en' },
    { text: 'stand up comedy', category: 'Entertainment', lang: 'en' },
    { text: 'escape room', category: 'Entertainment', lang: 'en' },
    { text: 'water park', category: 'Entertainment', lang: 'en' },
    { text: 'go kart', category: 'Entertainment', lang: 'en' },
    { text: 'paintball', category: 'Entertainment', lang: 'en' },
    { text: 'cinema hall', category: 'Entertainment', lang: 'banglish' },
    { text: 'movie dekhlam', category: 'Entertainment', lang: 'banglish' },
    { text: 'bondhuder sathe party', category: 'Entertainment', lang: 'banglish' },
    { text: 'birthday party', category: 'Entertainment', lang: 'banglish' },
    { text: 'cox bazar tour', category: 'Entertainment', lang: 'banglish' },
    { text: 'boat club', category: 'Entertainment', lang: 'banglish' },
    { text: 'game kinlam', category: 'Entertainment', lang: 'banglish' },
    { text: 'pubg uc', category: 'Entertainment', lang: 'banglish' },
    { text: 'netflix er bill', category: 'Entertainment', lang: 'banglish' },
    { text: 'ghurte jawa', category: 'Entertainment', lang: 'banglish' },
    { text: 'সিনেমা হল', category: 'Entertainment', lang: 'bangla' },
    { text: 'মুভি দেখলাম', category: 'Entertainment', lang: 'bangla' },
    { text: 'কক্সবাজার ভ্রমণ', category: 'Entertainment', lang: 'bangla' },
    { text: 'জাদুঘর', category: 'Entertainment', lang: 'bangla' },
    { text: 'চিড়িয়াখানা', category: 'Entertainment', lang: 'bangla' },
    { text: 'খেলার টিকিট', category: 'Entertainment', lang: 'bangla' },
    { text: 'কনসার্ট', category: 'Entertainment', lang: 'bangla' },
    { text: 'বনভোজন', category: 'Entertainment', lang: 'bangla' },
    { text: 'ঘুরতে গেলাম', category: 'Entertainment', lang: 'bangla' },
    { text: 'রিসোর্ট', category: 'Entertainment', lang: 'bangla' },

    // Education
    { text: 'exam registration', category: 'Education', lang: 'en' },
    { text: 'lab fee', category: 'Education', lang: 'en' },
    { text: 'thesis printing', category: 'Education', lang: 'en' },
    { text: 'coaching center', category: 'Education', lang: 'en' },
    { text: 'online class', category: 'Education', lang: 'en' },
    { text: 'language course', category: 'Education', lang: 'en' },
    { text: 'board exam fee', category: 'Education', lang: 'en' },
    { text: 'exam fees', category: 'Education', lang: 'en' },
    { text: 'tuition payment', category: 'Education', lang: 'en' },
    { text: 'course fee', category: 'Education', lang: 'en' },
    { text: 'khata kolom', category: 'Education', lang: 'banglish' },
    { text: 'school er beton', category: 'Education', lang: 'banglish' },
    { text: 'coaching er fee', category: 'Education', lang: 'banglish' },
    { text: 'vortir fee', category: 'Education', lang: 'banglish' },
    { text: 'porikkhar fee', category: 'Education', lang: 'banglish' },
    { text: 'tuition er taka dilam', category: 'Education', lang: 'banglish' },
    { text: 'hsc form fillup', category: 'Education', lang: 'banglish' },
    { text: 'guide boi', category: 'Education', lang: 'banglish' },
    { text: 'coaching e bhorti', category: 'Education', lang: 'banglish' },
    { text: 'porikkhar form', category: 'Education', lang: 'banglish' },
    { text: 'কোচিং ফি', category: 'Education', lang: 'bangla' },
    { text: 'ভর্তি পরীক্ষা', category: 'Education', lang: 'bangla' },
    { text: 'পরীক্ষার ফরম', category: 'Education', lang: 'bangla' },
    { text: 'টিউশন ফি দিলাম', category: 'Education', lang: 'bangla' },
    { text: 'বিশ্ববিদ্যালয়ের ফি', category: 'Education', lang: 'bangla' },
    { text: 'খাতা কলম', category: 'Education', lang: 'bangla' },
    { text: 'প্রাইভেট পড়ার বেতন', category: 'Education', lang: 'bangla' },
    { text: 'অনলাইন কোর্স', category: 'Education', lang: 'bangla' },
    { text: 'কলেজের বেতন', category: 'Education', lang: 'bangla' },
    { text: 'প্রশ্ন ব্যাংক', category: 'Education', lang: 'bangla' },

    // Personal Care
    { text: 'razor', category: 'Personal Care', lang: 'en' },
    { text: 'hair gel', category: 'Personal Care', lang: 'en' },
    { text: 'face mask', category: 'Personal Care', lang: 'en' },
    { text: 'trimmer', category: 'Personal Care', lang: 'en' },
    { text: 'haircut and shave', category: 'Personal Care', lang: 'en' },
    { text: 'skin care cream', category: 'Personal Care', lang: 'en' },
    { text: 'hair straightening', category: 'Personal Care', lang: 'en' },
    { text: 'hair removal cream', category: 'Personal Care', lang: 'en' },
    { text: 'aftershave', category: 'Personal Care', lang: 'en' },
    { text: 'hair mask', category: 'Personal Care', lang: 'en' },
    { text: 'salon e gelam', category: 'Personal Care', lang: 'banglish' },
    { text: 'parlour e gelam', category: 'Personal Care', lang: 'banglish' },
    { text: 'chul rong', category: 'Personal Care', lang: 'banglish' },
    { text: 'dari kamano', category: 'Personal Care', lang: 'banglish' },
    { text: 'gym er fee', category: 'Personal Care', lang: 'banglish' },
    { text: 'kapor dhulai', category: 'Personal Care', lang: 'banglish' },
    { text: 'istri kora', category: 'Personal Care', lang: 'banglish' },
    { text: 'sabun shampoo', category: 'Personal Care', lang: 'banglish' },
    { text: 'mehedi', category: 'Personal Care', lang: 'banglish' },
    { text: 'facial korlam', category: 'Personal Care', lang: 'banglish' },
    { text: 'চুল কাটালাম', category: 'Personal Care', lang: 'bangla' },
    { text: 'দাড়ি কামানো', category: 'Personal Care', lang: 'bangla' },
    { text: 'মেহেদি', category: 'Personal Care', lang: 'bangla' },
    { text: 'কাপড় ধোলাই', category: 'Personal Care', lang: 'bangla' },
    { text: 'ইস্ত্রি', category: 'Personal Care', lang: 'bangla' },
    { text: 'জিমের ফি', category: 'Personal Care', lang: 'bangla' },
    { text: 'পার্লারে গেলাম', category: 'Personal Care', lang: 'bangla' },
    { text: 'শ্যাম্পু কিনলাম', category: 'Personal Care', lang: 'bangla' },
    { text: 'লোশন', category: 'Personal Care', lang: 'bangla' },
    { text: 'নখ কাটা', category: 'Personal Care', lang: 'bangla' },

    // Salary
    { text: 'consulting income', category: 'Salary', lang: 'en' },
    { text: 'shop sales', category: 'Salary', lang: 'en' },
    { text: 'stipend', category: 'Salary', lang: 'en' },
    { text: 'scholarship', category: 'Salary', lang: 'en' },
    { text: 'prize money', category: 'Salary', lang: 'en' },
    { text: 'year end bonus', category: 'Salary', lang: 'en' },
    { text: 'client invoice paid', category: 'Salary', lang: 'en' },
    { text: 'side hustle income', category: 'Salary', lang: 'en' },
    { text: 'tutoring income', category: 'Salary', lang: 'en' },
    { text: 'dividend received', category: 'Salary', lang: 'en' },
    { text: 'beton dhukse', category: 'Salary', lang: 'banglish' },
    { text: 'mash shesher beton', category: 'Salary', lang: 'banglish' },
    { text: 'bonus dise', category: 'Salary', lang: 'banglish' },
    { text: 'client taka pathaise', category: 'Salary', lang: 'banglish' },
    { text: 'freelancing er taka', category: 'Salary', lang: 'banglish' },
    { text: 'dokan er bikri', category: 'Salary', lang: 'banglish' },
    { text: 'bhara pelam', category: 'Salary', lang: 'banglish' },
    { text: 'bidesh theke remittance', category: 'Salary', lang: 'banglish' },
    { text: 'abba taka dise', category: 'Salary', lang: 'banglish' },
    { text: 'tuition kore taka pelam', category: 'Salary', lang: 'banglish' },
    { text: 'মাসের বেতন', category: 'Salary', lang: 'bangla' },
    { text: 'বেতন ঢুকেছে', category: 'Salary', lang: 'bangla' },
    { text: 'উৎসব বোনাস', category: 'Salary', lang: 'bangla' },
    { text: 'রেমিট্যান্স', category: 'Salary', lang: 'bangla' },
    { text: 'দোকানের বিক্রি', category: 'Salary', lang: 'bangla' },
    { text: 'বাড়িভাড়া পেলাম', category: 'Salary', lang: 'bangla' },
    { text: 'বৃত্তির টাকা', category: 'Salary', lang: 'bangla' },
    { text: 'পুরস্কারের টাকা', category: 'Salary', lang: 'bangla' },
    { text: 'লাভের টাকা', category: 'Salary', lang: 'bangla' },
    { text: 'কমিশন পেলাম', category: 'Salary', lang: 'bangla' },
];
